const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const pipeline=[
{name:'景区输入',tool:'create_project'},{name:'地图空间理解',tool:'analyze_map'},{name:'文化资源检索',tool:'search_yongjia_knowledge'},{name:'开发潜力分析',tool:'analyze_potential'},{name:'IP 方向',tool:'generate_ip_directions'},{name:'世界观',tool:'build_world'},{name:'角色设计',tool:'design_characters'},{name:'剧情 × 空间',tool:'plan_story_route'},{name:'任务与线索',tool:'design_tasks_clues'},{name:'文化植入',tool:'integrate_culture'},{name:'AI 审查',tool:'review_and_fix'}];
const ipOptions=[
{id:'mystery',label:'B',name:'古村迷案',type:'悬疑探索',tagline:'七星八斗疑云',score:94,visual:'ov2',reason:'真实空间适合线索追踪，文化锚点可自然转译为谜题。'},
{id:'fantasy',label:'A',name:'山水秘境',type:'东方奇幻',tagline:'守护山河记忆',score:89,visual:'ov1',reason:'山水意象强，适合轻奇幻叙事与年轻游客拍照传播。'},
{id:'folklore',label:'C',name:'民俗奇闻',type:'民俗传奇',tagline:'古村旧事重现',score:86,visual:'ov3',reason:'适合将民俗、人物与建筑故事转成分段探索体验。'}];
const demoProject={
id:'YJ-AGENT-001',title:'七星照影',scenic:'楠溪江 · 芙蓉古村',style:'悬疑探索',audience:'年轻游客',duration:'90–120 分钟',status:'completed',score:92,
overview:{concept:'游客收到一封没有署名的旧信，在真实古村空间中寻找被打散的“照影星图”。每一次移动都对应一个剧情节点，每一处建筑细节都可能成为线索。',sellingPoint:'真实文化 × 真实空间 × 轻量解谜，让游客不是“听完一个故事”，而是在景区里完成这个故事。',interaction:'手机 Web / 图像识别 / 对话选择 / 空间观察',implementation:'轻量 H5 优先，关键节点可扩展 AR / NFC / 线下机关。'},
ip:{positioning:'以古村“七星八斗”空间意象为核心文化锚点，将古村建筑、山水与地方记忆转译为一场“复原失落星图”的悬疑探索。',worldview:'每一颗星，都照着一段没有被说完的村史。游客并不是旁观者，而是最后一位“寻星人”。',target:'18–35 岁年轻游客为主，同时兼顾亲子家庭与轻研学人群。',gameplay:'真实空间移动 + 文化观察 + 轻解谜 + NPC 对话 + 线索组合。',tags:['东方悬疑','古村探索','文化解谜','轻量剧游']},
characters:[
{name:'陆砚',role:'引导者 / NPC',desc:'年轻的村史讲解员，熟悉所有公开资料，却刻意回避关于“第八斗”的问题。',clue:'旧测绘册',relation:'知道最多，却只说一半'},
{name:'陶伯',role:'关键人物 / NPC',desc:'司马第守屋老人，相信星图从来不是传说。他知道一段被家族隐藏的往事。',clue:'砖雕拓片',relation:'掌握核心历史记忆'},
{name:'阿澜',role:'行动型 NPC',desc:'经营河岸小店的年轻人，掌握游客动线与近年村落变化，是现实线索的连接者。',clue:'水岸旧照',relation:'连接“过去”与“现在”'},
{name:'“寻星人”',role:'玩家身份',desc:'受一封无署名旧信引导来到古村，逐步拼回被打散的星图，并判断哪些是真史、哪些是演绎。',clue:'残缺星图',relation:'推动所有剧情节点'}],
plot:[
{act:'第一幕',subtitle:'进入故事',beats:[['旧信来客','玩家在村口获得残缺星图。'],['第一颗星','古街建筑细节触发首个线索。'],['被避开的问题','陆砚拒绝回答“第八斗”。']]},
{act:'第二幕',subtitle:'追踪与反转',beats:[['门楣拓印','司马第出现关键图样。'],['水纹刻度','线索从“星”转向“斗”。'],['旧测绘册','历史布局与剧情假设第一次发生冲突。']]},
{act:'第三幕',subtitle:'真相与回望',beats:[['第八斗','玩家发现真正缺失的是叙事而非地点。'],['照影成图','所有线索被重新排列。'],['终章水岸','玩家完成故事，也得到真实文化说明。']]}],
nodes:[
{id:1,name:'村口牌坊',status:'done',x:132,y:520,kind:'入口节点',story:'无署名旧信',summary:'玩家抵达村口，收到一封只写着“把七颗星送回原位”的旧信。',task:'确认寻星人身份',goal:'找到第一处星位标记',clue:'残缺星图',npc:'—',interaction:'扫码 / 开场动画',reward:'身份卡'},
{id:2,name:'芙蓉古街',status:'done',x:350,y:393,kind:'探索节点',story:'屋檐下的第一颗星',summary:'古街连续出现相同几何纹样，玩家需要观察真实建筑细节，判断哪一个与星图对应。',task:'完成建筑观察',goal:'找到匹配纹样',clue:'古街拓印',npc:'陆砚',interaction:'拍照识别 / 观察',reward:'星位 01'},
{id:3,name:'司马第大屋',status:'current',x:560,y:252,kind:'核心任务点',story:'消失的星图',summary:'门楣图样与残缺星图完全吻合，而屋内却少了一块本应存在的砖雕。',task:'补全七星图',goal:'观察建筑细节并推断缺失星位',clue:'砖雕拓片',npc:'陶伯',interaction:'图像识别 / 解谜',reward:'星图碎片'},
{id:4,name:'芙蓉亭',status:'locked',x:795,y:178,kind:'推理节点',story:'水纹刻度',summary:'亭边的水纹记号将“星图”引向另一套空间逻辑。',task:'理解水纹线索',goal:'把刻度与地图关联',clue:'水纹刻度',npc:'阿澜',interaction:'地图比对',reward:'路线提示'},
{id:5,name:'芙蓉峰',status:'locked',x:965,y:92,kind:'视野节点',story:'从高处看村落',summary:'当玩家从更高视角重新观察，之前分散的点位开始形成完整关系。',task:'完成空间重组',goal:'重新排列已收集线索',clue:'旧测绘册',npc:'陆砚',interaction:'拖拽组合',reward:'星位 05'},
{id:6,name:'七星八斗',status:'special',x:742,y:425,kind:'关键剧情',story:'不存在的第八颗星',summary:'玩家意识到“第八斗”并不是简单的宝藏点，而是故事故意制造的误导。',task:'辨别真实与演绎',goal:'判断三条叙事证据的真伪',clue:'第八斗注记',npc:'陶伯',interaction:'证据判断',reward:'真相页'},
{id:7,name:'水岸终章',status:'locked',x:920,y:525,kind:'终章节点',story:'七星照影',summary:'完整星图最终不是指向宝藏，而是把游客重新带回真实古村与山水。',task:'完成终章',goal:'提交最终推理',clue:'完整照影图',npc:'全部角色',interaction:'结局选择',reward:'电子纪念卡'}],
tasks:[['T01','寻找第一颗星','空间观察','村口 → 古街','残缺星图','拍照识别','低'],['T02','古街纹样比对','建筑观察','芙蓉古街','古街拓印','观察 / 选择','低'],['T03','补全七星图','核心解谜','司马第','砖雕拓片','图像识别','中'],['T04','水纹与地图','空间推理','芙蓉亭','水纹刻度','地图比对','中'],['T05','重组村落关系','线索组合','芙蓉峰','旧测绘册','拖拽组合','中'],['T06','判断“第八斗”','证据判断','七星八斗','三类证据','真假判断','中'],['T07','角色对质','剧情选择','河岸','NPC 口述','对话选择','低'],['T08','完成照影图','终章整合','水岸终章','全部碎片','组合 / 结局','中']],
clues:[['01','残缺星图','开场核心物件','村口牌坊'],['02','古街拓印','指向真实建筑图样','芙蓉古街'],['03','砖雕拓片','补全第三星位','司马第'],['04','水纹刻度','把星线索转向水系','芙蓉亭'],['05','旧测绘册','解释空间关系','芙蓉峰'],['06','第八斗注记','制造并破解核心误导','七星八斗'],['07','水岸旧照','连接过去与现实','河岸'],['08','完整照影图','终章结构化成果','终章']],
culture:[
{kind:'real',label:'真实文化',title:'古村空间格局与建筑文化',desc:'作为策划锚点。真实信息进入知识库后，才允许被剧情与任务引用。',state:'需来源验证',source:'景区资料 / 地方文献'},
{kind:'space',label:'真实空间',title:'村口、古街、传统建筑、亭台、河岸等',desc:'任务仅绑定地图或资料中已确认存在的空间，不新增虚构建筑。',state:'空间已匹配',source:'景区地图 / 点位资料'},
{kind:'real',label:'真实文化',title:'楠溪江山水与古村生活方式',desc:'用于形成整体叙事气质，并设计从建筑到水岸的体验节奏。',state:'高相关',source:'文旅知识库'},
{kind:'fiction',label:'剧情虚构',title:'“照影星图”与“寻星人”设定',desc:'原创游戏叙事，仅承担玩法连接作用，最终体验中需明确标注为剧情演绎。',state:'已标注',source:'Agent 创作'}],
assets:[
{id:'cover',name:'项目主视觉',type:'封面 / 海报',status:'ready',label:'七星照影',prompt:'东方极简文旅主视觉，楠溪江古村、水墨山水、淡青灰纸感、留白、年轻游客剪影、悬疑但克制，不生成任何文字。'},
{id:'hero',name:'寻星人主角立绘',type:'角色视觉',status:'ready',label:'寻星人',prompt:'中国年轻旅行者角色设定，全身立绘，青灰轻户外服装融合东方细节，携带残缺星图与铜质小牌，现代文旅 IP 风格，纸本淡彩。'},
{id:'npc1',name:'陆砚角色立绘',type:'NPC 视觉',status:'ready',label:'陆砚',prompt:'年轻村史讲解员，斯文克制，携带旧测绘册，古村背景淡化，东方写实插画。'},
{id:'npc2',name:'陶伯角色立绘',type:'NPC 视觉',status:'pending',label:'陶伯',prompt:'司马第守屋老人，温和但神秘，手持砖雕拓片，东方淡彩人物设定，真实质感。'},
{id:'map',name:'山水剧本地图',type:'地图视觉',status:'ready',label:'剧本地图',prompt:'将真实景区空间关系转译为东方山水手绘地图，保留入口、古街、古宅、亭台、山体、河岸的相对关系，路线清晰，不生成文字。'},
{id:'scene',name:'司马第剧情插画',type:'场景插画',status:'pending',label:'消失的星图',prompt:'古村大屋门楣与砖雕细节，傍晚柔光，游客正在观察一处缺失的图案，悬疑探索氛围，东方淡彩写实，不生成文字。'}],
implementation:{front:'移动端 H5 / Web',backend:'Node.js + Express',database:'PostgreSQL / Supabase / Railway PostgreSQL',storage:'对象存储（COS / S3）',ai:'主 Agent + 文旅 RAG + 多模态地图理解 + 生图 API',v1:['景区输入与资料上传','真实文化 RAG','地图空间理解','IP / 世界观 / 角色','剧情节点与任务线索','视觉资产任务队列','自动审查与项目持久化'],later:['AR / NFC 深度互动','线下机关控制','游客多人协作','景区运营数据接入']},
review:[['世界观一致性',96,'角色目标、主线与核心设定一致。'],['剧情逻辑',91,'已修复第 4 节点线索跳跃问题。'],['游戏可玩性',89,'任务类型有差异，避免连续纯阅读。'],['空间合理性',95,'主要任务均绑定已确认空间。'],['文化真实性',94,'真实资料与剧情虚构已分层标注。'],['实施可行性',88,'V1 采用轻量 Web 交互，减少硬件依赖。']],
fixes:['将“第八斗”从虚构地点改为剧情概念，避免与真实空间冲突。','把连续两次“阅读答题”改为建筑观察 + 地图比对，提高玩法差异。','在终章加入“真实文化 / 剧情演绎”标识，降低游客事实混淆。']};

const state={view:'home',stage:0,progress:12,selectedStyle:'悬疑探索',selectedIp:'mystery',scenic:'楠溪江 · 芙蓉古村',audience:'年轻游客',duration:'90–120 分钟',paused:false,running:false,logs:[],project:structuredClone(demoProject),activeNode:3,activeAsset:null,apiBase:localStorage.getItem('yongjia_api_base')||''};
const views={home:$('#view-home'),studio:$('#view-studio'),project:$('#view-project'),library:$('#view-library')};let runTimer=null;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2400)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]))}
function nowTime(){const d=new Date();return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function nav(name){Object.entries(views).forEach(([k,v])=>v.classList.toggle('active',k===name));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));state.view=name;window.scrollTo({top:0,behavior:'smooth'});if(name==='project')renderProject('overview');if(name==='library')window.dispatchEvent(new Event('projectlibraryopen'))}
$$('[data-nav]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();nav(b.dataset.nav)}));
$$('[data-open-demo]').forEach(el=>el.addEventListener('click',()=>nav('project')));
$('#heroStartBtn').addEventListener('click',()=>$('#createSection').scrollIntoView({behavior:'smooth',block:'center'}));
function syncMode(){const c=Boolean(state.apiBase);$('#modeText').textContent=c?'API 模式':'演示模式';$('#modeBtn').classList.toggle('connected',c);$('#mobileModeBtn').classList.toggle('connected',c);$('#mobileModeBtn span:last-child').textContent=c?'API':'Demo'}
function renderPipeline(){$('#pipeline').innerHTML=pipeline.map((s,i)=>`<li class="${i<state.stage?'done':i===state.stage?'active':''}"><span class="pnum">${i<state.stage?'✓':String(i+1).padStart(2,'0')}</span><span>${s.name}</span></li>`).join('');$('#stageTags').innerHTML=pipeline.map((s,i)=>`<span class="${i<state.stage?'done':i===state.stage?'current':''}">${i<state.stage?'✓ ':''}${s.name}</span>`).join('')}
function addLog(message,tool='project_planner'){state.logs.push({message,tool,time:nowTime()});renderActivity()}
function renderActivity(){const stream=$('#activityStream');stream.innerHTML=state.logs.map(l=>`<div class="activity-item"><div class="agent-avatar">山</div><div class="activity-bubble">${esc(l.message)}<div class="activity-meta"><span class="tool-inline">⌁ ${esc(l.tool)}</span><time>${l.time}</time></div></div></div>`).join('');$('#activityCount').textContent=`${state.logs.length} 条记录`;stream.scrollTop=stream.scrollHeight}
function renderTools(){const icons={create_project:'▦',analyze_map:'⌖',search_yongjia_knowledge:'文',analyze_potential:'◇',generate_ip_directions:'IP',build_world:'世',design_characters:'人',plan_story_route:'路',design_tasks_clues:'⌘',integrate_culture:'植',review_and_fix:'✓'};$('#toolList').innerHTML=pipeline.map((s,i)=>{const st=i<state.stage?'done':i===state.stage&&state.running?'running':'wait';return `<div class="tool-item"><span class="tool-icon">${icons[s.tool]||'·'}</span><div><b>${s.tool}</b><small>${s.name}</small></div><span class="tool-state ${st}">${st==='done'?'完成':st==='running'?'运行中':'等待'}</span></div>`}).join('')}
function renderEvidence(){const items=[['景区空间','地图 / 用户上传资料','只使用已确认存在的点位'],['文化知识','永嘉文旅知识库','真实文化与剧情演绎分层'],['玩法约束','剧本游设计规则','任务必须产生游客实际行动']];$('#evidenceList').innerHTML=items.map(x=>`<div class="evidence-card"><div><b>${x[0]}</b><span>${x[1]}</span></div><p>${x[2]}</p></div>`).join('')}
function updateStudio(){renderPipeline();renderTools();renderEvidence();$('#projectScenicName').textContent=state.scenic;$('#progressText').textContent=`${state.progress}%`;$('#progressBar').style.width=`${state.progress}%`;$('#agentStatus').textContent=state.paused?'已暂停':state.running?'运行中':state.progress>=100?'已完成':'等待中';$('#cancelRunBtn').textContent=state.paused?'继续':'暂停';const current=pipeline[Math.min(state.stage,pipeline.length-1)];$('#currentStageText').textContent=state.progress>=100?'已完成自动审查与修正':`当前：${current.name}`}
function resetRun(){clearInterval(runTimer);state.stage=0;state.progress=8;state.running=true;state.paused=false;state.logs=[];state.selectedIp='mystery';state.project=structuredClone(demoProject);state.project.storageId=null;state.project.style=state.selectedStyle;$('#decisionPanel').hidden=true;$('#completionPanel').hidden=true;addLog(`已创建「${state.scenic}」项目。目标游客：${state.audience}；预期游玩：${state.duration}；偏好：${state.selectedStyle}。`,'create_project');updateStudio()}
const stageMessages=['项目档案已建立，后续生成内容将保存为结构化资产，而不是只保留聊天文本。','正在理解景区空间。将入口、道路、建筑、公共空间与可交互点位建立为空间节点。','正在检索文化资源，并区分“真实文化事实”与“可用于剧情演绎的创作空间”。','正在评估哪些文化元素适合转化为剧情、任务、线索和游客实际行为。','已生成多个差异明显的 IP 方向，需要你只做一次关键选择。','已锁定 IP 方向，正在搭建世界规则、故事动机与叙事边界。','正在设计角色关系，并确保每个 NPC 都承担线索、引导或冲突功能。','正在把故事节点映射到真实空间，形成可走、可触发、可推进的游线。','正在生成任务链与线索链，避免连续问答，增加观察、组合与选择。','正在检查文化植入位置，确保真实内容有来源、虚构内容有标识。','执行自动审查：逻辑、可玩性、空间、文化真实性与实施可行性。'];
function startSimulation(){resetRun();nav('studio');runTimer=setInterval(()=>{if(state.paused)return;if(state.stage>=4){clearInterval(runTimer);state.running=false;state.progress=43;updateStudio();showDecision();return}state.stage+=1;state.progress=[13,22,31,38,43][state.stage]||43;addLog(stageMessages[state.stage],pipeline[state.stage].tool);updateStudio()},850)}
function renderIpOptions(){$('#ipOptions').innerHTML=ipOptions.map(o=>`<button class="ip-option ${state.selectedIp===o.id?'selected':''}" data-ip="${o.id}"><div class="option-visual ${o.visual}"></div><div class="option-copy"><small>${o.label} · 推荐度 ${o.score}</small><h3>${o.name}</h3><p>${o.type} · ${o.tagline}</p><div class="option-score"><span>文化 ${o.score}</span><span>空间 ${Math.max(82,o.score-2)}</span><span>传播 ${Math.max(80,o.score-5)}</span></div><em>${o.reason}</em></div></button>`).join('');$$('.ip-option').forEach(b=>b.addEventListener('click',()=>{state.selectedIp=b.dataset.ip;renderIpOptions()}))}
function showDecision(){renderIpOptions();$('#decisionPanel').hidden=false;$('#decisionPanel').scrollIntoView({behavior:'smooth',block:'center'})}
function continueSimulation(){$('#decisionPanel').hidden=true;state.running=true;state.stage=5;state.progress=49;const chosen=ipOptions.find(x=>x.id===state.selectedIp);state.project.style=chosen.type;addLog(`已选择「${chosen.name} / ${chosen.type}」方向。Agent 将继续自动生成后续模块。`,'generate_ip_directions');updateStudio();let step=5;clearInterval(runTimer);runTimer=setInterval(()=>{if(state.paused)return;if(step>=10){clearInterval(runTimer);state.stage=11;state.progress=100;state.running=false;addLog('审查完成：发现 3 个可修正问题，已自动完成局部修正并再次审查通过。','review_and_fix');updateStudio();$('#completionPanel').hidden=false;saveProject();$('#completionPanel').scrollIntoView({behavior:'smooth',block:'center'});return}step+=1;state.stage=step;state.progress={6:60,7:70,8:80,9:88,10:96}[step]||55;addLog(stageMessages[step],pipeline[Math.min(step,10)].tool);updateStudio()},780)}
function saveProject(){state.project.scenic=state.scenic;state.project.audience=state.audience;state.project.duration=state.duration;state.project.style=state.project.style||state.selectedStyle;localStorage.setItem('yongjia_demo_project',JSON.stringify(state.project));window.dispatchEvent(new Event('projectlocalsaved'))}
function loadSavedProject(){try{const raw=localStorage.getItem('yongjia_demo_project');if(raw){state.project={...state.project,...JSON.parse(raw)};state.scenic=state.project.scenic||state.scenic;state.audience=state.project.audience||state.audience;state.duration=state.project.duration||state.duration}}catch(e){}}
$('#startBtn').addEventListener('click',()=>{const scenic=$('#scenicInput').value.trim();if(!scenic){toast('请先输入景区名称');return}state.scenic=scenic;state.audience=$('#audienceSelect').value;state.duration=$('#durationSelect').value;startSimulation()});
$('#exampleBtn').addEventListener('click',()=>{$('#scenicInput').value='楠溪江 · 芙蓉古村';$('#audienceSelect').value='年轻游客';$('#durationSelect').value='90–120 分钟';state.selectedStyle='悬疑探索';$$('#styleChips button').forEach(b=>b.classList.toggle('active',b.dataset.style==='悬疑探索'));toast('已载入比赛演示案例')});
$$('#styleChips button').forEach(b=>b.addEventListener('click',()=>{state.selectedStyle=b.dataset.style;$$('#styleChips button').forEach(x=>x.classList.toggle('active',x===b))}));
$('#mapUpload').addEventListener('change',e=>{const f=e.target.files[0];if(f){$('#mapFileName').textContent=f.name;toast('地图已加入项目输入')}});$('#materialUpload').addEventListener('change',e=>{const n=e.target.files.length;if(n){$('#materialFileName').textContent=`已选择 ${n} 个文件`;toast(`已加入 ${n} 个景区资料文件`)}});
$('#confirmDirection').addEventListener('click',continueSimulation);$('#cancelRunBtn').addEventListener('click',()=>{if(!state.running&&state.progress<100){toast('当前没有正在运行的任务');return}state.paused=!state.paused;updateStudio();toast(state.paused?'已暂停演示流程':'已继续运行')});$('#openProjectBtn').addEventListener('click',()=>nav('project'));
function projectHeaderSync(){const p=state.project;$('#projectTitle').textContent=`《${p.title}》`;$('#projectSubtitle').textContent=`${p.scenic} · ${p.style}`;$('#projectTagSummary').innerHTML=`<span>${p.nodes.length} 个剧情节点</span><span>${p.tasks.length} 个任务</span><span>${p.clues.length} 条线索</span><span>${p.characters.length} 位角色</span>`}
function renderProject(tab='overview'){projectHeaderSync();$$('#projectTabs button').forEach(b=>b.classList.toggle('active',b.dataset.projectTab===tab));const c=$('#projectContent'),p=state.project;const templates={
overview:()=>`<section class="project-content"><div class="overview-grid"><article class="overview-main"><span class="overview-kicker">PROJECT CONCEPT</span><h2>${p.overview.sellingPoint}</h2><p>${p.overview.concept}</p><div class="metric-grid"><div class="metric"><b>${p.nodes.length}</b><span>剧情节点</span></div><div class="metric"><b>${p.tasks.length}</b><span>任务</span></div><div class="metric"><b>${p.clues.length}</b><span>核心线索</span></div><div class="metric"><b>${p.score}</b><span>AI 审查分</span></div></div></article><aside class="overview-side"><h3>项目摘要</h3><div class="summary-row"><span>目标游客</span><b>${p.audience}</b></div><div class="summary-row"><span>游玩时长</span><b>${p.duration}</b></div><div class="summary-row"><span>交互方式</span><b>${p.overview.interaction}</b></div><div class="summary-row"><span>实施策略</span><b>${p.overview.implementation}</b></div></aside></div><div class="deliverables-strip"><article class="deliverable-mini"><i>◇</i><b>IP / 世界观</b><span>已结构化</span></article><article class="deliverable-mini"><i>⌖</i><b>剧情地图</b><span>${p.nodes.length} 个节点</span></article><article class="deliverable-mini"><i>⌘</i><b>任务系统</b><span>${p.tasks.length} 个任务</span></article><article class="deliverable-mini"><i>文</i><b>文化植入</b><span>${p.culture.length} 类证据</span></article><article class="deliverable-mini"><i>▦</i><b>视觉资产</b><span>${p.assets.length} 个任务</span></article><article class="deliverable-mini"><i>◫</i><b>游客端</b><span>H5 体验预览</span></article></div><div class="project-logic-card"><div><small>PROJECT LOGIC</small><h3>真实文化 → 真实空间 → 剧情节点 → 任务 → 线索 → 游客行为</h3></div><button class="ghost-btn compact" data-jump-tab="map">查看空间绑定 →</button></div></section>`,
map:()=>renderMapTab(),
ip:()=>`<section class="project-content"><div class="detail-grid"><article class="content-card"><small>IP 定位</small><h2>${p.title}</h2><p>${p.ip.positioning}</p><div class="tag-row">${p.ip.tags.map(t=>`<span>${t}</span>`).join('')}</div></article><article class="content-card"><small>一句话世界观</small><h3>“${p.ip.worldview}”</h3><p>世界观只服务于真实景区体验，不凭空制造新的景点与历史事实。</p></article><article class="content-card"><small>目标游客</small><h3>${p.ip.target}</h3><p>将游玩节奏与信息密度控制在大众游客可完成的范围内。</p></article><article class="content-card"><small>核心玩法</small><h3>${p.ip.gameplay}</h3><p>游戏机制隐藏在旅行行为里，用户感受到的是探索，而不是复杂 RPG 系统。</p></article></div></section>`,
characters:()=>`<section class="project-content"><div class="character-grid">${p.characters.map((ch,i)=>`<article class="character-card"><div class="character-art ca${i+1}"><span>${ch.name.slice(0,1)}</span></div><div class="character-copy"><small>${ch.role}</small><h3>${ch.name}</h3><p>${ch.desc}</p><div class="relation"><b>关系：</b>${ch.relation}</div><div class="relation"><b>持有线索：</b>${ch.clue}</div></div></article>`).join('')}</div></section>`,
plot:()=>`<section class="project-content"><div class="plot-timeline">${p.plot.map(act=>`<article class="plot-act"><div class="act-label">${act.act}<small>${act.subtitle}</small></div><div class="plot-beats">${act.beats.map((b,i)=>`<div class="plot-beat"><span>${String(i+1).padStart(2,'0')}</span><b>${b[0]}</b><p>${b[1]}</p></div>`).join('')}</div></article>`).join('')}</div></section>`,
tasks:()=>`<section class="project-content"><div class="section-note"><b>任务设计原则</b><span>每个任务必须让游客产生实际行为，而不是连续阅读与答题。</span></div><div class="table-card"><table class="data-table"><thead><tr><th>ID</th><th>任务</th><th>类型</th><th>空间</th><th>核心线索</th><th>互动</th><th>难度</th></tr></thead><tbody>${p.tasks.map(t=>`<tr><td>${t[0]}</td><td><b>${t[1]}</b></td><td><span class="type-tag">${t[2]}</span></td><td>${t[3]}</td><td>${t[4]}</td><td>${t[5]}</td><td>${t[6]}</td></tr>`).join('')}</tbody></table></div></section>`,
clues:()=>`<section class="project-content"><div class="clue-flow-head"><small>CLUE CHAIN</small><h2>线索不是独立物件，而是推动下一次空间移动的因果链。</h2></div><div class="clue-chain">${p.clues.map((x,i)=>`<article class="clue-card"><strong>${x[0]}</strong><h3>${x[1]}</h3><p>${x[2]}</p><span>来源：${x[3]}</span>${i<p.clues.length-1?'<i>→</i>':''}</article>`).join('')}</div></section>`,
culture:()=>`<section class="project-content"><div class="culture-legend"><span class="real">真实文化</span><span class="space">真实空间</span><span class="fiction">剧情虚构</span><p>最终游客端应明确区分“文化事实”和“剧情演绎”。</p></div><div class="culture-stack">${p.culture.map(x=>`<article class="culture-item"><span class="culture-kind ${x.kind}">${x.label}</span><div><h3>${x.title}</h3><p>${x.desc}</p><small>来源：${x.source}</small></div><b>${x.state}</b></article>`).join('')}</div></section>`,
visitor:()=>renderVisitorTab(),
assets:()=>renderAssetsTab(),
implementation:()=>renderImplementationTab(),
review:()=>`<section class="project-content"><div class="review-summary"><div class="score-ring">${p.score}</div><div><small>AI REVIEW / 2 ROUNDS</small><h2>项目通过自动审查与局部修正</h2><p>系统不是“生成完就结束”，而是检查问题、定位影响范围、自动修正并重新审查。</p></div></div><div class="review-grid">${p.review.map(r=>`<article class="review-item"><div><span>${r[0]}</span><b>${r[1]}</b></div><div class="review-bar"><i style="--score:${r[1]}%"></i></div><p>${r[2]}</p></article>`).join('')}</div><div class="review-fixes"><h3>本轮已自动修正</h3><ol>${p.fixes.map(f=>`<li>${f}</li>`).join('')}</ol></div></section>`};c.innerHTML=(templates[tab]||templates.overview)();bindDynamic(tab)}
function renderMapTab(){const p=state.project,n=p.nodes.find(x=>x.id===state.activeNode)||p.nodes[2];const nodeSvg=p.nodes.map(x=>`<g class="map-node ${x.status} ${x.id===n.id?'selected':''}" data-node="${x.id}" transform="translate(${x.x} ${x.y})"><circle r="${x.id===n.id?28:22}"/><text text-anchor="middle" dy="5">${x.id}</text><foreignObject x="-66" y="32" width="132" height="40"><div class="map-node-label">${x.name}</div></foreignObject></g>`).join('');return `<section class="project-content"><div class="map-layout"><div class="story-map-card"><div class="map-toolbar"><button>⌖ 总览</button><button>◎ 定位</button><span>点击节点查看剧情与任务</span></div><svg class="story-map-svg" viewBox="0 0 1100 650"><path class="river" d="M0 470 C160 370 258 410 360 322 C464 234 536 337 645 252 C772 155 899 220 1100 94"/><path class="route" d="M132 520 C205 469 278 436 350 393 C425 347 495 297 560 252 C650 208 727 217 795 178 C861 141 910 112 965 92 M560 252 C635 310 690 363 742 425 C790 479 850 509 920 525"/><g class="mountains"><path d="M30 260Q115 90 220 265"/><path d="M245 225Q345 56 460 240"/><path d="M700 168Q820 0 930 170"/></g>${nodeSvg}</svg><div class="map-legend"><span><i class="done"></i>已完成</span><span><i class="current"></i>当前</span><span><i class="special"></i>关键剧情</span><span><i class="locked"></i>未解锁</span></div></div><aside class="node-panel"><div class="node-panel-head"><span class="node-index">${n.id}</span><div><h2>${n.name}</h2><small>${n.kind}</small></div><button>♡</button></div><article class="node-story"><small>剧情</small><h3>${n.story}</h3><p>${n.summary}</p><div class="meta-pills"><span>真实空间</span><span>剧情节点</span><span>${n.interaction}</span></div></article><article class="node-task"><small>当前任务</small><h3>${n.task}</h3><p>${n.goal}</p><div class="task-facts"><div><small>关键线索</small><b>${n.clue}</b></div><div><small>相关 NPC</small><b>${n.npc}</b></div><div><small>互动方式</small><b>${n.interaction}</b></div><div><small>任务奖励</small><b>${n.reward}</b></div></div></article></aside></div></section>`}
function renderVisitorTab(){const n=state.project.nodes.find(x=>x.id===state.activeNode)||state.project.nodes[2];return `<section class="project-content visitor-preview-wrap"><div class="visitor-copy"><small>VISITOR EXPERIENCE</small><h2>游客看到的不是“策划后台”，而是一段正在发生的旅行故事。</h2><p>后台生成的地图、剧情、任务和线索，会被压缩成轻量移动端体验。游戏机制隐藏在旅行行为里。</p><div class="visitor-principles"><span>地图是空间骨架</span><span>剧情解释“为什么去”</span><span>任务告诉“到那里做什么”</span></div><div class="visitor-node-list">${state.project.nodes.slice(0,5).map(x=>`<button class="visitor-node ${x.id===state.activeNode?'active':''}" data-visitor-node="${x.id}"><b>${x.id}</b><span>${x.name}<small>${x.story}</small></span></button>`).join('')}</div></div><div class="phone-shell"><div class="phone-notch"></div><div class="phone-screen"><header><span>‹</span><div><b>七星照影</b><small>${state.project.scenic}</small></div><i>···</i></header><div class="phone-map"><svg viewBox="0 0 360 250"><path d="M0 176 C70 130 104 158 153 112 C202 70 244 109 291 61 C319 33 340 38 360 25"/><path class="route" d="M42 205 C100 180 124 153 177 120 C224 89 265 82 321 54"/>${state.project.nodes.slice(0,5).map(x=>`<circle cx="${36+x.x*.28}" cy="${226-x.y*.27}" r="${x.id===state.activeNode?10:7}" class="${x.id===state.activeNode?'active':''}"/>`).join('')}</svg></div><article class="phone-story"><span class="phone-step">0${n.id}</span><div><small>${n.kind}</small><h3>${n.story}</h3><p>${n.summary}</p></div></article><article class="phone-task"><small>当前任务</small><h3>${n.task}</h3><p>${n.goal}</p><button>查看任务详情 →</button></article><nav><span>◌<small>对话</small></span><span class="active">⌖<small>故事</small></span><span>▱<small>线索</small></span></nav></div></div></section>`}
function renderAssetsTab(){return `<section class="project-content"><div class="asset-toolbar"><div><small>VISUAL ASSET PIPELINE</small><h2>视觉资产不是手工补图，而是 Agent 生成任务的一部分。</h2><p>后端可接 Seedream / GPT Image 等图片 API。提示词由结构化角色、场景和风格资产自动组装。</p></div><button class="primary-btn compact" id="generateAllAssets">批量生成待生成资产</button></div><div class="asset-grid">${state.project.assets.map(a=>`<article class="asset-card" data-asset="${a.id}"><button class="asset-preview ${a.status==='generating'?'generating':''} ${a.status==='ready'?'ready':''}" data-asset-open="${a.id}"><span>${a.status==='generating'?'生成中…':a.label}</span><small>${a.type}</small></button><div class="asset-copy"><div><h3>${a.name}</h3><button class="asset-generate" data-asset-id="${a.id}">${a.status==='ready'?'重新生成':a.status==='generating'?'生成中':'生成'}</button></div><p>${a.status==='ready'?'已生成演示预览':'等待生图 API'} · 点击预览查看 Prompt</p></div></article>`).join('')}</div><div class="asset-api-note"><b>生产环境</b><span>浏览器 → Railway 后端 → 图片 API → 对象存储 → 返回图片 URL。API Key 永远不进入前端代码。</span></div></section>`}
function renderImplementationTab(){const i=state.project.implementation;return `<section class="project-content"><div class="implementation-hero"><small>IMPLEMENTATION</small><h2>从比赛 Demo 到景区真实使用，分两层部署。</h2><p>V1 先跑通“策划生产闭环”，再逐步增加游客现场互动与景区运营系统。</p></div><div class="implementation-grid"><article><small>前端</small><h3>${i.front}</h3><p>景区策划后台 + 游客移动端 H5，共用项目数据。</p></article><article><small>后端</small><h3>${i.backend}</h3><p>Main Agent、工具调用、API 鉴权与任务编排。</p></article><article><small>数据</small><h3>${i.database}</h3><p>保存结构化 Project，而不是仅依赖聊天记录。</p></article><article><small>存储</small><h3>${i.storage}</h3><p>保存上传地图、资料与 AI 生成视觉资产。</p></article></div><div class="phase-grid"><article><span>V1 / 比赛与首个真实景区</span><h3>必须完成</h3><ul>${i.v1.map(x=>`<li>✓ ${x}</li>`).join('')}</ul></article><article><span>V2 / 深化体验</span><h3>后续扩展</h3><ul>${i.later.map(x=>`<li>＋ ${x}</li>`).join('')}</ul></article></div><div class="deploy-flow"><span>GitHub</span><b>→</b><span>Railway / Node.js</span><b>→</b><span>Main Agent</span><b>→</b><span>LLM / RAG / Image API</span><b>→</b><span>PostgreSQL + Object Storage</span></div></section>`}
function bindDynamic(tab){$$('[data-jump-tab]').forEach(b=>b.addEventListener('click',()=>renderProject(b.dataset.jumpTab)));if(tab==='map')$$('.map-node').forEach(n=>n.addEventListener('click',()=>{state.activeNode=Number(n.dataset.node);renderProject('map')}));if(tab==='visitor')$$('[data-visitor-node]').forEach(n=>n.addEventListener('click',()=>{state.activeNode=Number(n.dataset.visitorNode);renderProject('visitor')}));if(tab==='assets'){ $$('.asset-generate').forEach(btn=>btn.addEventListener('click',()=>generateAsset(btn.dataset.assetId)));$$('[data-asset-open]').forEach(btn=>btn.addEventListener('click',()=>openAssetModal(btn.dataset.assetOpen)));$('#generateAllAssets')?.addEventListener('click',()=>{state.project.assets.filter(a=>a.status!=='ready').forEach((a,i)=>setTimeout(()=>generateAsset(a.id),i*400))})}}
function generateAsset(id){const a=state.project.assets.find(x=>x.id===id);if(!a||a.status==='generating')return;a.status='generating';renderProject('assets');setTimeout(()=>{a.status='ready';renderProject('assets');toast(`${a.name} 已生成演示预览`)},1200)}
function openAssetModal(id){const a=state.project.assets.find(x=>x.id===id);if(!a)return;state.activeAsset=id;$('#assetModalTitle').textContent=a.name;$('#assetModalDesc').textContent=`${a.type} · 当前状态：${a.status==='ready'?'已生成':'等待生成'}`;$('#assetPromptText').textContent=a.prompt;openModal('#assetModal')}
$('#assetModalGenerate').addEventListener('click',()=>{if(state.activeAsset){closeModals();generateAsset(state.activeAsset)}});
$$('#projectTabs button').forEach(b=>b.addEventListener('click',()=>renderProject(b.dataset.projectTab)));
$('#exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state.project,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${state.project.title}-project.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),100);toast('项目 JSON 已导出')});$('#printBtn').addEventListener('click',()=>window.print());$('#shareBtn').addEventListener('click',()=>toast('已生成演示分享入口；接后端后可生成真实项目链接'));
function openModal(id){$(id).hidden=false}function closeModals(){$$('.modal-backdrop').forEach(m=>m.hidden=true)}
$('#settingsBtn').addEventListener('click',()=>{$('#apiBaseInput').value=state.apiBase;openModal('#settingsModal')});$('#modeBtn').addEventListener('click',()=>{$('#apiBaseInput').value=state.apiBase;openModal('#settingsModal')});$('#mobileModeBtn').addEventListener('click',()=>{$('#apiBaseInput').value=state.apiBase;openModal('#settingsModal')});$$('[data-close-modal]').forEach(b=>b.addEventListener('click',closeModals));$$('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModals()}));
$('#saveApiBtn').addEventListener('click',()=>{state.apiBase=$('#apiBaseInput').value.trim().replace(/\/$/,'');if(state.apiBase)localStorage.setItem('yongjia_api_base',state.apiBase);else localStorage.removeItem('yongjia_api_base');syncMode();closeModals();toast(state.apiBase?'已切换为 API 模式':'已使用演示模式')});$('#clearApiBtn').addEventListener('click',()=>{$('#apiBaseInput').value='';state.apiBase='';localStorage.removeItem('yongjia_api_base');syncMode();$('#apiTestResult').textContent='尚未测试';toast('已恢复演示模式')});
$('#testApiBtn').addEventListener('click',async()=>{const base=$('#apiBaseInput').value.trim().replace(/\/$/,'');if(!base){$('#apiTestResult').textContent='请先填写 API 地址';return}const out=$('#apiTestResult');out.textContent='正在连接…';try{const ctl=new AbortController();setTimeout(()=>ctl.abort(),4500);const r=await fetch(`${base}/api/health`,{signal:ctl.signal});if(!r.ok)throw new Error();out.textContent='✓ 后端连接正常';out.className='ok'}catch(e){out.textContent='连接失败（演示模式不受影响）';out.className='bad'}});
$('#modifyBtn').addEventListener('click',()=>openModal('#modifyModal'));$$('.quick-prompts button').forEach(b=>b.addEventListener('click',()=>{$('#modifyInput').value=b.textContent;analyzeImpact()}));$('#modifyInput').addEventListener('input',analyzeImpact);function analyzeImpact(){const t=$('#modifyInput').value;let impact='等待输入修改要求…';if(/角色|反派|NPC/.test(t))impact='角色 → 相关对话 → 相关线索 → 局部审查';else if(/任务|解谜|互动|AR|NFC/.test(t))impact='任务 → 线索 → 互动机制 → 可玩性审查';else if(/风格|世界观|整体/.test(t))impact='IP → 世界观 → 角色 → 剧情 → 任务（影响较大）';else if(/文化|历史|民俗/.test(t))impact='文化资源 → 剧情引用 → 任务 / 线索 → 真实性审查';else if(t.trim())impact='Agent 将读取依赖关系后确定最小影响范围';$('#impactPreview span').textContent=impact}
$('#applyModifyBtn').addEventListener('click',()=>{if(!$('#modifyInput').value.trim()){toast('请先输入修改要求');return}const b=$('#applyModifyBtn');b.disabled=true;b.textContent='Agent 正在分析影响…';setTimeout(()=>{b.disabled=false;b.innerHTML='分析并应用修改 <span>→</span>';closeModals();toast('已完成局部修改演示，并保留未受影响模块')},1100)});
loadSavedProject();syncMode();renderPipeline();renderEvidence();renderTools();renderActivity();

